### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by aertist** [JCBrouwer/maua-style#3]
please update the readme and add how to use this so noobs like me can also use this awesome tool :)

**Comment by JCBrouwer** [comment]
Thanks for your interest! I'm working on it. One issue is that different features currently only work in their own branch. Merging is going to be quite a bit of work, but hopefully it'll happen soon enough.

**Comment by aertist** [comment]
Any updates regarding this repo? 👀

**Comment by JCBrouwer** [comment]
Yes two weeks ago I made a big dent in the tasks that needed to be done. It's probably in a place where it works well enough now I guess. I'm working on the last bits of the configuration (GPU-related and ffmpeg-related settings) in the branch `better-config`. Once those are done I'll write up the documentation and installation instructions. I'm very busy this week+next, but maybe next weekend I'll have some time to do this.

**Comment by aertist** [comment]
Hey, I'm a newbie and will learn many things by seeing your implementation of style transfer for videos. Thanks for open sourcing this project.

Also I saw the code but didnt found any way to run it from cli. Any plans to add cli args?

**Comment by JCBrouwer** [comment]
Yes, you should checkout the better-config branch:
```
git clone https://github.com/JCBrouwer/maua-style/.git
git checkout better-config
```

Then you can see all the arguments in [config.py](https://github.com/JCBrouwer/maua-style/blob/better-config/config.py) or by running `python style.py --help`

You can run a video style transfer with:
```
python style.py -content /path/to/video -style /path/to/image1 /path/to/image2 etc. -transfer_type vid_img
```

I haven't gone through this on a clean install yet, so you'll probably need to install some packages. You also will need to clone https://github.com/sniklaus/pytorch-unflow to the same folder as maua-style.

As I said, the repo is pretty close to camera ready, so the errors should hopefully be simple to solve with configuration + some package installation

**Comment by entangledothers** [comment]
How exactly is the pytorch-unflow repo integrated? Having tried adding it, it keeps stranding on "ModuleNotFoundError: No module named 'sniklaus.unflow.run'.

**Comment by JCBrouwer** [comment]
It's included as a submodule so you need to either `git clone --recursive https://github.com/JCBrouwer/maua-style.git` or if you've already cloned `git submodule update`. That should pull in those repositories as well.

**Comment by JCBrouwer** [comment]
Hello @aertist @entangledothers , I've finally gone through and added usage information to the README!
